# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PA3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='office',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
